### ISSUE TITLE
Error when I run "pip install -e ."

### ISSUE THREAD

**Issue by ronaldpan** [Wuziyi616/multi_part_assembly#17]
Collecting scipy>=1.6.0 (from pyntcloud->multi-part-assembly==0.2.0)
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3367, in _dep_map
    return self.__dep_map
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3147, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_parser.py", line 214, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_parser.py", line 229, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    torch (>=1.8.*)
           ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_internal/metadata/pkg_resources.py", line 247, in iter_dependencies
    return self._dist.requires(extras)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3070, in requires
    dm = self._dep_map
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3369, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3379, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3434, in __init__
    super().__init__(requirement_string)
  File "/root/anaconda3/envs/assembly0/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    torch (>=1.8.*)

**Comment by Wuziyi616** [comment]
Hummm, I never saw this error before. Searched a bit and [this](https://github.com/pypa/pipx/issues/998) seems to be the closest one. Maybe you want to downgrade pip and retry?

Also this error seems to be triggered by a package that requires torch. Maybe you can try manually install all packages [here](https://github.com/Wuziyi616/multi_part_assembly/blob/master/setup.py#L3) instead of letting the code figure out dependencies? I don't really remember the exact version of these packages, but I think pytorch around 1.10 should work

**Comment by ronaldpan** [comment]
After I updated the pip version 
pip install pip==24
the issues fixed.

**Comment by Wuziyi616** [comment]
Glad that it works. So for training, as stated [here](https://github.com/Wuziyi616/multi_part_assembly/blob/master/docs/usage.md#training), you need to use the full path of the config file, e.g. `configs/global/global-32x1-cosine_200e-everyday.py`
