### ISSUE TITLE
Problem with scripts/vis.py

### ISSUE THREAD

**Issue by EdoardoBonanni** [Wuziyi616/multi_part_assembly#5]
Hi,
There is a problem with this file because the program crashes due to the following bug:
'rotation must be a tensor' in multi_part_assembly/utils/rotation.py in _check_valid function.
In this case self._rot is a map object instead of a tensor, and the assert blocks execution.
What should I do to fix the problem?

**Comment by EdoardoBonanni** [comment]
My setup is to use pointnet coding, RGL-net as model, task assembly of type geometric and artifact as dataset.

**Comment by Wuziyi616** [comment]
Can you put your config file here, so that I can run it to check what's wrong?

**EDIT**: or can you provide more information? E.g. the full error message indicating which line is wrong.

**Comment by crtie** [comment]
I meet the same question, here's my full error message
Traceback (most recent call last):
  File "scripts/vis.py", line 134, in <module>
    visualize(cfg)
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "scripts/vis.py", line 36, in visualize
    out_dict = model(batch)  # trans/rot: [B, P, 3/4/(3, 3)]
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 69, in gather_map
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 69, in <genexpr>
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/home/vipuser/miniconda3/envs/PA_tcr/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 73, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/vipuser/multi_part_assembly/multi_part_assembly/utils/rotation.py", line 119, in __init__
    self._check_valid()
  File "/home/vipuser/multi_part_assembly/multi_part_assembly/utils/rotation.py", line 139, in _check_valid
    assert isinstance(self._rot, torch.Tensor), 'rotation must be a tensor'
AssertionError: rotation must be a tensor

**Comment by Wuziyi616** [comment]
Thanks for the info. Which model are you testing? Is this problem associated with one model or all of them?

**Comment by crtie** [comment]
I trained dgl and LSTM following your usage.md and try to vis their results, but both model met this problem.

**Comment by Wuziyi616** [comment]
That's weird. I try the `vis.py` but I can pass that line (and trigger a bug in the line after `loss_dict, _ = model.module._calc_loss(out_dict, batch)`) Have you pull the newest code from `master` branch? Or are you using `dev` branch?

**Comment by crtie** [comment]
yeah，I pulled the newest code from master branch just yesterday. And it goes well when I run train.py and test.py

**Comment by crtie** [comment]
okay! I already fixed this bug by cancel the DataParallel wrpper. I know this may decrease efficienfy, but it's enough for me. Thank for your prompt reply.
Here is my changed vis.py
![图片](https://user-images.githubusercontent.com/61133940/219829599-97bc2e38-6315-4e18-a633-579eb4cb7908.png)

**Comment by Wuziyi616** [comment]
Ah, I think I understand where the problem is. Yes, the current code won't work with multi-gpu. I'll fix it. Thanks for providing insights here!

**Comment by Wuziyi616** [comment]
Fixed in the latest commit
